-- MySQL Script generated by MySQL Workbench
-- Qua 10 Set 2014 16:17:20 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campanha` (
  `idCampanha` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idCampanha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nivel` (
  `IdNivel` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`IdNivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agentes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Campanha_idCampanha` INT NOT NULL,
  `barra` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Nivel_IdNivel` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Agente_Campanha1_idx` (`Campanha_idCampanha` ASC),
  INDEX `fk_Agente_Nivel1_idx` (`Nivel_IdNivel` ASC),
  CONSTRAINT `fk_Agente_Campanha1`
    FOREIGN KEY (`Campanha_idCampanha`)
    REFERENCES `mydb`.`Campanha` (`idCampanha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agente_Nivel1`
    FOREIGN KEY (`Nivel_IdNivel`)
    REFERENCES `mydb`.`Nivel` (`IdNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `id` INT NOT NULL,
  `nome_estado` VARCHAR(45) NULL,
  `sigla` CHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `id` INT NOT NULL,
  `nome_cidade` VARCHAR(45) NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidades_estados1` (`idestado` ASC),
  CONSTRAINT `fk_cidades_estados1`
    FOREIGN KEY (`idestado`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bairros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bairros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idcidade` INT NOT NULL,
  `nome_bairro` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bairros_cidades1` (`idcidade` ASC),
  CONSTRAINT `fk_bairros_cidades1`
    FOREIGN KEY (`idcidade`)
    REFERENCES `mydb`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quadras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quadras` (
  `idQuadra` INT NOT NULL AUTO_INCREMENT,
  `identificacao` VARCHAR(20) NULL,
  `Agente_id` INT NOT NULL,
  `Bairro_id` INT NOT NULL,
  PRIMARY KEY (`idQuadra`, `Bairro_id`),
  INDEX `fk_Quadra_Agente1_idx` (`Agente_id` ASC),
  INDEX `fk_Quadra_Bairro1_idx` (`Bairro_id` ASC),
  CONSTRAINT `fk_Quadra_Agente1`
    FOREIGN KEY (`Agente_id`)
    REFERENCES `mydb`.`agentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quadra_Bairro1`
    FOREIGN KEY (`Bairro_id`)
    REFERENCES `mydb`.`bairros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoImovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoImovel` (
  `idTipoImovel` INT NOT NULL AUTO_INCREMENT,
  `sigla` CHAR(2) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoImovel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rua` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_rua` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imovel` (
  `idImovel` INT NOT NULL AUTO_INCREMENT,
  `quantidade_habitantes` INT NULL,
  `idTipoImovel` INT NOT NULL,
  `quantidade_caes` INT NULL,
  `quantidade_gatos` INT NULL,
  `numero_imovel` VARCHAR(10) NULL,
  `ladoquadra` INT NOT NULL,
  `Rua_id` INT NOT NULL,
  `Quadra_idQuadra` INT NOT NULL,
  `Quadra_Bairro_id` INT NOT NULL,
  PRIMARY KEY (`idImovel`),
  INDEX `fk_imoveis_tipos1` (`idTipoImovel` ASC),
  INDEX `fk_imovel_Rua1_idx` (`Rua_id` ASC),
  INDEX `fk_imovel_Quadra1_idx` (`Quadra_idQuadra` ASC, `Quadra_Bairro_id` ASC),
  CONSTRAINT `fk_imoveis_tipos1`
    FOREIGN KEY (`idTipoImovel`)
    REFERENCES `mydb`.`TipoImovel` (`idTipoImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_Rua1`
    FOREIGN KEY (`Rua_id`)
    REFERENCES `mydb`.`rua` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_Quadra1`
    FOREIGN KEY (`Quadra_idQuadra` , `Quadra_Bairro_id`)
    REFERENCES `mydb`.`quadras` (`idQuadra` , `Bairro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoAtividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoAtividade` (
  `idTipoAtividade` INT NOT NULL,
  `sigla` VARCHAR(4) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoAtividade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visita` (
  `id` INT NOT NULL,
  `idimovel` INT NOT NULL,
  `hora` TIME NULL,
  `pendencia` TINYINT(1) NULL DEFAULT false,
  `data` DATE NULL,
  `ciclo` INT NULL,
  `TipoAtividade_idTipoAtividade` INT NOT NULL,
  `TipoVisita_idTipoVisita` INT NOT NULL,
  `recuperada` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visitas_imoveis1` (`idimovel` ASC),
  INDEX `fk_Visita_TipoAtividade1_idx` (`TipoAtividade_idTipoAtividade` ASC),
  CONSTRAINT `fk_visitas_imoveis1`
    FOREIGN KEY (`idimovel`)
    REFERENCES `mydb`.`imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visita_TipoAtividade1`
    FOREIGN KEY (`TipoAtividade_idTipoAtividade`)
    REFERENCES `mydb`.`TipoAtividade` (`idTipoAtividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tratamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tratamento` (
  `quantidade_depositos_eliminados` INT NULL,
  `imovel_tratado` TINYINT(1) NULL,
  `quantidade_larvicida` FLOAT NULL,
  `quantidade_deposito_tratado` INT NULL,
  `TipoAtividade_idTipoAtividade` INT NOT NULL,
  `tipo_larvicida` CHAR(2) NULL,
  PRIMARY KEY (`TipoAtividade_idTipoAtividade`),
  CONSTRAINT `fk_Tratamento_TipoAtividade1`
    FOREIGN KEY (`TipoAtividade_idTipoAtividade`)
    REFERENCES `mydb`.`TipoAtividade` (`idTipoAtividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pesquisa` (
  `A1` INT NULL COMMENT 'Caixa d\'agua',
  `A2` INT NULL COMMENT 'Outros depósitos de armazenamento de água (baixo).',
  `B` INT NULL COMMENT 'Pequenos depósitos móveis.',
  `C` INT NULL COMMENT 'Depósito fixo.',
  `D1` INT NULL COMMENT 'Pneus e outros materais rodantes',
  `D2` INT NULL COMMENT 'Lixo (recipientes, plásticos, latas), sucatas, entulhos.',
  `E` INT NULL COMMENT 'Depósitos naturais.',
  `nr_amostra_inicial` INT NULL,
  `nr_amostra_final` INT NULL,
  `quantidade_tubitos` INT NULL,
  `TipoAtividade_idTipoAtividade` INT NOT NULL,
  PRIMARY KEY (`TipoAtividade_idTipoAtividade`),
  CONSTRAINT `fk_Pesquisa_TipoAtividade1`
    FOREIGN KEY (`TipoAtividade_idTipoAtividade`)
    REFERENCES `mydb`.`TipoAtividade` (`idTipoAtividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ciclo` (
  `idciclo` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `numero` INT NOT NULL COMMENT 'O número do ciclo é calculado através do ano base e do último número do ciclo.',
  `anoBase` INT NOT NULL,
  PRIMARY KEY (`idciclo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agente_has_Ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agente_has_Ciclo` (
  `Agente_id` INT NOT NULL,
  `Ciclo_idciclo` INT NOT NULL,
  PRIMARY KEY (`Agente_id`, `Ciclo_idciclo`),
  INDEX `fk_Agente_has_Ciclo_Ciclo1_idx` (`Ciclo_idciclo` ASC),
  INDEX `fk_Agente_has_Ciclo_Agente1_idx` (`Agente_id` ASC),
  CONSTRAINT `fk_Agente_has_Ciclo_Agente1`
    FOREIGN KEY (`Agente_id`)
    REFERENCES `mydb`.`agentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agente_has_Ciclo_Ciclo1`
    FOREIGN KEY (`Ciclo_idciclo`)
    REFERENCES `mydb`.`Ciclo` (`idciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ciclo_has_Quadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ciclo_has_Quadra` (
  `Ciclo_idciclo` INT NOT NULL,
  `Quadra_idQuadra` INT NOT NULL,
  `Quadra_Bairro_id` INT NOT NULL,
  PRIMARY KEY (`Ciclo_idciclo`, `Quadra_idQuadra`, `Quadra_Bairro_id`),
  INDEX `fk_Ciclo_has_Quadra_Quadra1_idx` (`Quadra_idQuadra` ASC, `Quadra_Bairro_id` ASC),
  INDEX `fk_Ciclo_has_Quadra_Ciclo1_idx` (`Ciclo_idciclo` ASC),
  CONSTRAINT `fk_Ciclo_has_Quadra_Ciclo1`
    FOREIGN KEY (`Ciclo_idciclo`)
    REFERENCES `mydb`.`Ciclo` (`idciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ciclo_has_Quadra_Quadra1`
    FOREIGN KEY (`Quadra_idQuadra` , `Quadra_Bairro_id`)
    REFERENCES `mydb`.`quadras` (`idQuadra` , `Bairro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `test` ;
USE `test` ;